/* ═══ CHECKLIST TEMPLATES — generated from CSV files ═══ */

const g = (id, label) => ({ id, label, checked: false });

const INTERNAL_CHECKLIST = {
  id: "inst_internal_checklist",
  name: "Internal Checklist",
  accessLevel: "open",
  type: "checklist",
  items: [],
  milestones: [
    { id: "int_ms_1", name: "1. Design & CAD Release", description: "Finalize CAD, BOM, and cross-functional review.", color: "#00C9A7", checklist: [
      g("int_1_1",   "CAD Finalized"),
      g("int_1_1_1", "CAD GD&T — critical dimensions highlighted as CTQs"),
      g("int_1_1_2", "CAD drawing packet available in PDF format"),
      g("int_1_1_3", "Acceptable tolerances and clear definitions for critical specs (e.g. working distance)"),
      g("int_1_2",   "Mounting interfaces validated for station and line compatibility"),
      g("int_1_3",   "BOM finalized and approved"),
      g("int_1_4",   "Scoping document released"),
      g("int_1_5",   "Cross-functional internal review of scope (SA + CSE + TPM) completed"),
    ], links: [], signatures: [] },
    { id: "int_ms_2", name: "2. Machine Shop / Fabrication Readiness", description: "Prepare fabrication docs and confirm lead times.", color: "#3B82F6", checklist: [
      g("int_2_1", "CAD and drawing shared with machine shop"),
      g("int_2_2", "Lead times confirmed (timeline with deployment / material availability confirmed)"),
      g("int_2_3", "Assembly instructions documented (if non-trivial)"),
      g("int_2_4", "Factory dimensional validation POC and procedure documented to ensure design compliance"),
    ], links: [], signatures: [] },
    { id: "int_ms_3", name: "3. Custom Parts & Procurement", description: "Identify, order, and track all parts.", color: "#F59E0B", checklist: [
      g("int_3_1", "All parts identified as either MTO/OTS (Made to Order / Off the Shelf)"),
      g("int_3_2", "Long lead items flagged, tracked, and ordered in advance if necessary"),
      g("int_3_3", "Spare parts identified and ordered"),
      g("int_3_4", "All parts in house to be assembled and ready for shipment"),
      g("int_3_5", "Lead times for MTOs confirmed"),
    ], links: [], signatures: [] },
    { id: "int_ms_4", name: "4. System Integration Readiness", description: "Validate compute, network, power, and cable requirements.", color: "#A855F7", checklist: [
      g("int_4_1", "Compute hardware sized for workload"),
      g("int_4_2", "Network requirements defined"),
      g("int_4_3", "Power requirements defined"),
      g("int_4_4", "Cable length requirements validated vs real layout"),
      g("int_4_5", "All required cables/adapters included in BOM"),
      g("int_4_6", "Extra hardware scoped and prepped in advance of shipment"),
    ], links: [], signatures: [] },
    { id: "int_ms_5", name: "5. Software & Data Readiness, FAT", description: "Validate software, data, and FAT readiness.", color: "#0284C7", checklist: [
      g("int_5_1", "Unit tracking / barcode logic verified"),
      g("int_5_2", "Data storage + access confirmed"),
      g("int_5_3", "Offline fallback plan defined (if network drops)"),
    ], links: [], signatures: [] },
    { id: "int_ms_6", name: "6. Deployment Planning", description: "Define location, schedule, and dry run.", color: "#DC2626", checklist: [
      g("int_6_1", "Exact station location defined and documented clearly"),
      g("int_6_2", "Installation procedure documented"),
      g("int_6_3", "Daily deployment schedule established"),
      g("int_6_4", "Dry run or simulation completed (if possible)"),
    ], links: [], signatures: [] },
    { id: "int_ms_7", name: "7. Internal Sign Off", description: "TPM, SA, and CSE formal approvals.", color: "#64748B", checklist: [
      g("int_7_1", "TPM Approval"),
      g("int_7_2", "SA Approval"),
      g("int_7_3", "CSE Approval"),
    ], links: [], signatures: [
      { id: "int_sig_tpm", role: "TPM", name: "", email: "", signed: false, signedAt: null },
      { id: "int_sig_sa",  role: "SA",  name: "", email: "", signed: false, signedAt: null },
      { id: "int_sig_cse", role: "CSE", name: "", email: "", signed: false, signedAt: null },
    ] },
  ],
};

const EXTERNAL_CHECKLIST = {
  id: "inst_external_checklist",
  name: "External Checklist",
  accessLevel: "open",
  type: "checklist",
  items: [],
  milestones: [
    { id: "ext_ms_1", name: "1. Security & Onsite Readiness", description: "Clearances, entry logistics, and onsite requirements.", color: "#00C9A7", checklist: [
      g("ext_1_1",   "Obtained/provided all necessary documentation for security and internet clearance"),
      g("ext_1_1_1", "Tools check in"),
      g("ext_1_1_2", "Ease and location of factory entry / exit"),
      g("ext_1_1_3", "Prior knowledge of food availability"),
      g("ext_1_1_4", "Customer / CM oversight necessity of IN employees"),
    ], links: [], signatures: [] },
    { id: "ext_ms_2", name: "2. Line Access & Production Readiness", description: "Alignment, downtime, and safety approvals.", color: "#3B82F6", checklist: [
      g("ext_2_1",   "Customer + CM alignment meeting"),
      g("ext_2_1_1", "Supervisors, leads, and operators aware of deployment timing"),
      g("ext_2_1_2", "Necessary personnel involved in alignment / kick-off meeting"),
      g("ext_2_1_3", "Clear dates, actions, and owners for open items with follow-up cadence"),
      g("ext_2_1_4", "Business value to CM shared"),
      g("ext_2_2",   "Production line scheduled downtime confirmed"),
      g("ext_2_2_1", "Line will be fully stopped during installation"),
      g("ext_2_2_2", "Shift schedule and ability to work after hours"),
      g("ext_2_3",   "Safety approvals cleared (lockout/tagout if needed)"),
      g("ext_2_4",   "PPE requirements conveyed"),
      g("ext_2_4_1", "Customer / Instrumental to provide PPE"),
      g("ext_2_4_2", "Understanding requirements: eye glasses, steel-toed shoes, coat, ear coverings"),
      g("ext_2_5",   "Physical access to station location guaranteed"),
    ], links: [], signatures: [] },
    { id: "ext_ms_3", name: "3. Station Location & Layout", description: "Confirm install location, layout, and mounting.", color: "#F59E0B", checklist: [
      g("ext_3_1",   "Installation location confirmed and documented"),
      g("ext_3_2",   "Installation location cleared and evidence provided"),
      g("ext_3_3",   "Conveyed distance from power source, ethernet port, and production intent location"),
      g("ext_3_3_1", "Power source distance confirmed"),
      g("ext_3_3_2", "Ethernet port distance confirmed"),
      g("ext_3_3_3", "Installation vs production intent location representativeness confirmed"),
      g("ext_3_4",   "Mounting surface available and compatible"),
      g("ext_3_5",   "Space constraints reviewed (no interference with operators)"),
      g("ext_3_6",   "Line process flow compatible"),
    ], links: [], signatures: [] },
    { id: "ext_ms_4", name: "4. Network & IT Requirements", description: "Internet, IP, firewall, and cable requirements.", color: "#A855F7", checklist: [
      g("ext_4_1",     "Internet access need confirmed"),
      g("ext_4_1_1",   "Yes → Confirm connectivity available"),
      g("ext_4_1_1_1", "Confirm ability to bring adapters in case of internet down"),
      g("ext_4_1_2",   "No → Confirm offline workflow"),
      g("ext_4_2",     "Required IP addresses provided to customer IT and Instrumental TPM / FDE"),
      g("ext_4_3",     "Firewall rules configured (whitelisting Instrumental endpoints)"),
      g("ext_4_4",     "Ethernet ports active and tested"),
      g("ext_4_5",     "Network speed sufficient for high-res image transfer"),
      g("ext_4_6",     "Correct cable type available (CAT6 or higher) or escalated to Instrumental TPM"),
      g("ext_4_7",     "Cable length sufficient for actual layout"),
    ], links: [], signatures: [] },
    { id: "ext_ms_5", name: "5. Equipment Handling & Logistics", description: "Delivery, storage, and tooling.", color: "#0284C7", checklist: [
      g("ext_5_1", "Equipment delivered and stored safely"),
      g("ext_5_2", "Designated workspace to store and use equipment / tools"),
      g("ext_5_3", "Access for moving equipment to line confirmed"),
      g("ext_5_4", "Required tools available onsite (or brought by team)"),
      g("ext_5_5", "Local support contact identified"),
      g("ext_5_6", "Test sample ready to be used for setup and inspection"),
    ], links: [], signatures: [] },
    { id: "ext_ms_6", name: "6. Validation & Production Integration (SAT)", description: "Golden units, defect samples, and acceptance criteria.", color: "#DC2626", checklist: [
      g("ext_6_1", "Golden units available for validation"),
      g("ext_6_2", "Known defect samples available"),
      g("ext_6_3", "Cycle time expectations defined"),
      g("ext_6_4", "Acceptance criteria and type (SAT vs FAT) agreed and quantitatively defined"),
    ], links: [], signatures: [] },
    { id: "ext_ms_7", name: "7. Coordination & Communication", description: "Stakeholder matrix and escalation paths.", color: "#64748B", checklist: [
      g("ext_7_1",   "External stakeholder matrix clearly assigned"),
      g("ext_7_1_1", "CM: Key POC, IT POC, Process Engineer, PM, Manager"),
      g("ext_7_1_2", "Customer: Assigned POC, assigned manager"),
      g("ext_7_2",   "Escalation path defined by type of issue and level"),
      g("ext_7_2_1", "Level 1 = CM Point of contact"),
      g("ext_7_2_2", "Level 2 = Customer Point of contact"),
      g("ext_7_2_3", "Level 3 = CM management"),
      g("ext_7_2_4", "Level 4 = Customer management"),
      g("ext_7_3",   "Language / shift coordination considered (if global site)"),
    ], links: [], signatures: [] },
    { id: "ext_ms_8", name: "8. Final Pre-Deployment Confirmation", description: "Line, infrastructure, IT, and personnel all ready.", color: "#059669", checklist: [
      g("ext_8_1", "Line ready"),
      g("ext_8_2", "Infrastructure ready"),
      g("ext_8_3", "IT ready"),
      g("ext_8_4", "Personnel ready"),
      g("ext_8_5", "Anticipating risks and proactive mitigation prior to onsite presence"),
    ], links: [], signatures: [] },
  ],
};

const SI_CHECKLIST = {
  id: "inst_si_checklist",
  name: "SI Deployment Checklist",
  accessLevel: "open",
  type: "checklist",
  items: [],
  milestones: [
    { id: "si_ms_1", name: "1. SIRD Drafting", description: "Define imaging, mechanical, and automation requirements.", color: "#00C9A7", checklist: [
      g("si_1_1", "[Internal] Scope AOI use case with customer and site (product, inspection type, line layout)"),
      g("si_1_2", "[Internal] Define imaging requirements (camera type, lens, lighting, working distance, resolution)"),
      g("si_1_3", "[Internal] Define mechanical requirements (fixture dimensions, mounting interfaces, GD&T, CTQs)"),
      g("si_1_4", "[Internal] Define automation requirements (cycle time target, UPH target, motion control type)"),
      g("si_1_5", "[Internal] Define performance specs: Target UPH, cycle time/unit, automation sequence budget"),
      g("si_1_6", "[Internal] Include calibration and validation procedures (aperture, focus, gain)"),
      g("si_1_7", "[Internal] Include 2D drawings and provide 3D CAD models of imaging hardware to SI"),
      g("si_1_8", "[Internal] SIRD version-controlled and stored in shared repository"),
      g("si_1_9", "[External] Customer confirms product scope, inspection priorities, and line/site details"),
    ], links: [], signatures: [] },
    { id: "si_ms_2", name: "2. SIRD Approved", description: "Cross-functional review and SI acknowledgement.", color: "#3B82F6", checklist: [
      g("si_2_1", "[Internal] Cross-functional review completed: HDE / SA / TPM / Product Mgmt reviewed and approved SIRD"),
      g("si_2_2", "[Internal] SIRD version number locked"),
      g("si_2_3", "[Both] SI acknowledged receipt and confirmed understanding of SIRD"),
      g("si_2_4", "[Both] Customer (OEM) acknowledged and approved SIRD scope"),
      g("si_2_5", "[Internal] SIRD sent to SI with all referenced drawings and CAD files"),
      g("si_2_6", "[Internal] SIRD templatization status confirmed (reusable for future deployments)"),
    ], links: [], signatures: [
      { id: "si_sig_2_hde", role: "HDE", name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_2_sa",  role: "SA",  name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_2_tpm", role: "TPM", name: "", email: "", signed: false, signedAt: null },
    ] },
    { id: "si_ms_3", name: "3. DFM (SI)", description: "SI DFM package review — mechanical, electrical, safety.", color: "#F59E0B", checklist: [
      g("si_3_1", "[Internal] SI DFM package received (mechanical fixture design, automation layout, electrical design)"),
      g("si_3_2", "[Internal] Mechanical fixture design reviewed: dimensions, tolerances, material selection"),
      g("si_3_3", "[Internal] Layout drawings reviewed: line integration, space constraints, operator access"),
      g("si_3_4", "[Internal] Automation design reviewed: motion control, conveyors, lifters, gantry systems"),
      g("si_3_5", "[Internal] Camera module mounting and positioning validated against SIRD imaging specs"),
      g("si_3_6", "[Internal] Safety features reviewed: e-stops, light curtains, guards, lockout/tagout"),
      g("si_3_7", "[Internal] Cable routing and length requirements validated vs real factory layout"),
      g("si_3_8", "[Internal] Power and compressed air supply requirements documented"),
      g("si_3_9", "[External] CM/Customer confirms line layout compatibility and installation location dimensions"),
    ], links: [], signatures: [] },
    { id: "si_ms_4", name: "4. DFM Approved", description: "Formal DFM approval and BOM / station provisioning.", color: "#A855F7", checklist: [
      g("si_4_1",  "[Internal] DFM formally approved by Instrumental (SA + HDE + TPM sign-off)"),
      g("si_4_2",  "[Internal] Any design changes from original SIRD documented via change-order process"),
      g("si_4_3",  "[Internal] Impact on cost, schedule, and performance assessed for any deviations"),
      g("si_4_4",  "[Internal] Hardware responsibility confirmed: SI sourcing per IN spec OR IN consigning to SI"),
      g("si_4_5",  "[Internal] Cameras procured/allocated (type, qty)"),
      g("si_4_6",  "[Internal] Lenses procured/allocated (type, qty)"),
      g("si_4_7",  "[Internal] Lighting procured/allocated (type, qty)"),
      g("si_4_8",  "[Internal] Edge AI PC / station computer sized and procured"),
      g("si_4_9",  "[Internal] Monitor(s) procured"),
      g("si_4_10", "[Internal] All cables, adapters, connectors, stacklights, barcode scanners included"),
      g("si_4_11", "[Internal] BOM finalized: all parts identified as MTO or OTS, long lead items flagged"),
      g("si_4_12", "[Internal] 3D CAD models of all IN-supplied hardware delivered to SI"),
      g("si_4_13", "[Internal] Station provisioning kicked off"),
      g("si_4_14", "[Internal] Station type(s) confirmed: Manual / Semi-auto / Fully automated"),
      g("si_4_15", "[Internal] Project ID / Project Name / Scope documented"),
      g("si_4_16", "[Internal] Target shipping date for provisioned stations confirmed"),
      g("si_4_17", "[Internal] Number of stations to provision confirmed"),
    ], links: [], signatures: [
      { id: "si_sig_4_sa",  role: "SA",  name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_4_hde", role: "HDE", name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_4_tpm", role: "TPM", name: "", email: "", signed: false, signedAt: null },
    ] },
    { id: "si_ms_5", name: "5. Quote Received", description: "SI quote review — scope, pricing, terms, warranty.", color: "#0284C7", checklist: [
      g("si_5_1", "[Internal] SI quote received covering: design, fabrication, integration, shipping, installation, spare parts"),
      g("si_5_2", "[Internal] Quote includes subsystem responsibility split (SI vs Instrumental vs site-provided)"),
      g("si_5_3", "[Internal] Shipping term and destination explicit (Incoterm)"),
      g("si_5_4", "[Internal] Quote validity period and currency confirmed"),
      g("si_5_5", "[Internal] Warranty duration and coverage confirmed in quote"),
      g("si_5_6", "[Internal] Change-order process and pricing rules included"),
      g("si_5_7", "[Internal] Quote reviewed against Appendix A minimum fields (per Exec Memo)"),
    ], links: [], signatures: [] },
    { id: "si_ms_6", name: "6. Quote Approved", description: "Pricing confirmed, SOW executed, NDA in place.", color: "#DC2626", checklist: [
      g("si_6_1", "[Internal] Quote pricing confirmed acceptable by Instrumental and customer"),
      g("si_6_2", "[Internal] Payment milestone schedule agreed (e.g. 60/20/20)"),
      g("si_6_3", "[Internal] Customer (OEM) budget confirmed"),
      g("si_6_4", "[Both] Ownership & title transfer model confirmed"),
      g("si_6_5", "[Both] Warranty start trigger defined (e.g. SAT sign-off date)"),
      g("si_6_6", "[Internal] SI framework agreement or SOW executed"),
      g("si_6_7", "[Internal] NDA with SI executed; IP protection / station hardening plan confirmed"),
      g("si_6_8", "[Internal] Asset tagging and serialization plan agreed"),
    ], links: [], signatures: [] },
    { id: "si_ms_7", name: "7. PO Issued", description: "PO to SI, build schedule baselined, site prep begins.", color: "#64748B", checklist: [
      g("si_7_1",  "[Both] PO issued to SI; SI confirms receipt and kickoff date"),
      g("si_7_2",  "[Internal] SI build schedule received and baselined: BOM → Fabrication → Assembly → Debug → FAT"),
      g("si_7_3",  "[Internal] Milestone dates aligned with deployment target date"),
      g("si_7_4",  "[Both] Weekly/biweekly build status cadence established with SI"),
      g("si_7_5",  "[Internal] SI material lead times confirmed and tracked"),
      g("si_7_6",  "[Internal] Station provisioning onboarding form completed"),
      g("si_7_7",  "[Internal] Station type(s) confirmed"),
      g("si_7_8",  "[Internal] Project ID / Project Name / Scope confirmed"),
      g("si_7_9",  "[Internal] Shipping date for provisioned stations to SI or site confirmed"),
      g("si_7_10", "[Internal] Station computer provisioned with OS, Instrumental software, and image stream config"),
      g("si_7_11", "[Internal] AI models trained and validated for target product; model deployed to edge device"),
      g("si_7_12", "[Internal] Automated review thresholds set"),
      g("si_7_13", "[External] Customer + CM + SI + Instrumental alignment meeting completed"),
      g("si_7_14", "[External] Stakeholder matrix documented (Customer POC, CM POC, SI PM, Instrumental TPM/SA/HDE/CSE)"),
      g("si_7_15", "[External] Escalation path defined: L1 CM > L2 SI > L3 Customer > L4 Instrumental > L5 Management"),
      g("si_7_16", "[External] Installation location confirmed on floor plan; area clearing scheduled"),
      g("si_7_17", "[External] Power drops, network drops, compressed air confirmed at station location"),
      g("si_7_18", "[External] IT readiness: IP addresses provided, firewall rules configured, ethernet ports tested"),
      g("si_7_19", "[External] MES integration requirements defined (protocol, endpoints, data fields, test environment)"),
      g("si_7_20", "[External] Security clearance initiated for Instrumental + SI installation teams"),
    ], links: [], signatures: [] },
    { id: "si_ms_8", name: "8. Build", description: "SI fabrication, debugging, station receipt, site prep.", color: "#059669", checklist: [
      g("si_8_1",  "[Internal] L/T materials purchased by SI"),
      g("si_8_2",  "[Internal] Structure, standard ME parts, electrical parts purchased"),
      g("si_8_3",  "[Internal] Mechanical assembly complete"),
      g("si_8_4",  "[Internal] Electrical assembly complete"),
      g("si_8_5",  "[Internal] PLC/PC program loaded and I/O check complete"),
      g("si_8_6",  "[Both] Phase 1: Communication testing with Instrumental (offline) — verify station software connects"),
      g("si_8_7",  "[Internal] Single machine debugging and trial run complete"),
      g("si_8_8",  "[Internal] Whole line trial run complete (if multi-station deployment)"),
      g("si_8_9",  "[Internal] Provisioned station computers shipped to SI (or directly to site)"),
      g("si_8_10", "[Internal] SI confirms receipt of all Instrumental-supplied hardware (cameras, lenses, lights, PCs)"),
      g("si_8_11", "[Internal] Hardware integrated into SI-built fixture/cell"),
      g("si_8_12", "[External] Installation location physically cleared; evidence provided (photos)"),
      g("si_8_13", "[External] Floor load capacity verified for automated equipment"),
      g("si_8_14", "[External] Loading dock, forklift, rigging equipment confirmed for receiving"),
      g("si_8_15", "[External] Pathway from dock to install location cleared and measured"),
      g("si_8_16", "[External] Production line downtime scheduled and confirmed for installation window"),
      g("si_8_17", "[External] Safety review of automated equipment completed by site safety team"),
      g("si_8_18", "[External] PPE requirements communicated; who provides confirmed"),
      g("si_8_19", "[External] Golden units and known defect samples prepared for validation"),
      g("si_8_20", "[External] Operator scheduling: operators identified for training and initial production runs"),
    ], links: [], signatures: [] },
    { id: "si_ms_9", name: "9. FAT (Factory Acceptance Test)", description: "FAT criteria, execution, and sign-off.", color: "#F59E0B", checklist: [
      g("si_9_1",  "[Both] FAT date confirmed; Instrumental personnel attending identified"),
      g("si_9_2",  "[Both] FAT criteria documented and agreed between Instrumental and SI"),
      g("si_9_3",  "[Internal] Mechanical: fixture dimensions within tolerance, smooth motion on all axes"),
      g("si_9_4",  "[Internal] Imaging: camera focus, aperture, gain calibrated; image quality meets SIRD spec"),
      g("si_9_5",  "[Internal] Automation: cycle time within budget, all motion sequences operational"),
      g("si_9_6",  "[Internal] Software: Instrumental app connects, images upload successfully, health checks pass"),
      g("si_9_7",  "[Internal] Safety: e-stops functional, guards in place, lockout/tagout verified"),
      g("si_9_8",  "[Internal] Electrical: all I/O functional, wiring per schematic, power consumption within spec"),
      g("si_9_9",  "[Internal] Barcode/unit tracking: scanner reads correctly, serial numbers captured"),
      g("si_9_10", "[Internal] Data: images transfer at required resolution and speed"),
      g("si_9_11", "[Both] FAT Result: PASS / CONDITIONAL PASS / FAIL"),
      g("si_9_12", "[Internal] FAT sign-off: Instrumental SA and SI QA signatures"),
      g("si_9_13", "[Internal] If Conditional Pass: improvement items tracked and verified before shipment"),
    ], links: [], signatures: [
      { id: "si_sig_9_sa",    role: "Instrumental SA", name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_9_si_qa", role: "SI QA",            name: "", email: "", signed: false, signedAt: null },
    ] },
    { id: "si_ms_10", name: "10. Shipped", description: "Packaging, shipping, customs, and receiving coordination.", color: "#3B82F6", checklist: [
      g("si_10_1", "[Both] SI packing per agreed standards; fragile components secured"),
      g("si_10_2", "[Both] Anti-static packaging for electronic components confirmed"),
      g("si_10_3", "[Both] Shipping method confirmed: Sea / Air / Ground; Incoterm confirmed"),
      g("si_10_4", "[Both] Transit time aligned with deployment schedule; ETA at site confirmed"),
      g("si_10_5", "[Both] Insurance and risk of loss during transit assigned per SOW"),
      g("si_10_6", "[Both] Customs documentation prepared (commercial invoice, packing list, COO if applicable)"),
      g("si_10_7", "[External] Receiving contact and location confirmed at destination site"),
      g("si_10_8", "[External] Equipment storage location designated and secured"),
      g("si_10_9", "[External] Unloading equipment available (forklift, pallet jack, crane if needed)"),
    ], links: [], signatures: [] },
    { id: "si_ms_11", name: "11. SAT (Site Acceptance Test)", description: "Installation, commissioning, SAT criteria, and sign-off.", color: "#A855F7", checklist: [
      g("si_11_1",  "[Both] SI installation team onsite; Instrumental deployment team onsite"),
      g("si_11_2",  "[Both] Equipment moved from storage to installation location; rigging complete"),
      g("si_11_3",  "[Both] Station installed and leveled at final production location"),
      g("si_11_4",  "[Both] All connections verified: power, network, compressed air, cameras, PLC, MES"),
      g("si_11_5",  "[Internal] Instrumental software operational and communicating; health checks pass"),
      g("si_11_6",  "[Internal] Image stream and data stream configuration verified in production environment"),
      g("si_11_7",  "[Both] Golden unit validation passed"),
      g("si_11_8",  "[Both] Known defect sample detection verified"),
      g("si_11_9",  "[Both] Cycle time meets target UPH in production environment"),
      g("si_11_10", "[Both] Automation sequences operational in production"),
      g("si_11_11", "[Both] MES integration verified (data flowing to/from line systems)"),
      g("si_11_12", "[Both] Barcode scanning and serial number capture working"),
      g("si_11_13", "[Both] Operator training completed"),
      g("si_11_14", "[Both] 24hr/48hr production run completed without critical failures"),
      g("si_11_15", "[Both] SAT Result: PASS / CONDITIONAL PASS / FAIL"),
      g("si_11_16", "[Both] SAT sign-off: IN TPM, SI, CM/Customer signatures"),
      g("si_11_17", "[Both] If PASS: Warranty clock starts. Station officially enters production."),
    ], links: [], signatures: [
      { id: "si_sig_11_tpm",      role: "IN TPM",      name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_11_si",       role: "SI",          name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_11_customer", role: "CM/Customer", name: "", email: "", signed: false, signedAt: null },
    ] },
    { id: "si_ms_12", name: "12. Warranty / Legal Window", description: "Post-SAT monitoring, SLA enforcement, final payment.", color: "#DC2626", checklist: [
      g("si_12_1",  "[Internal] Warranty window start date confirmed (= SAT pass date)"),
      g("si_12_2",  "[Internal] Monitoring period: station performance tracked daily during warranty window"),
      g("si_12_3",  "[Internal] Key metrics monitored: uptime %, UPH achieved, false alarm rate, image quality"),
      g("si_12_4",  "[Internal] Any defects or failures documented with root cause and resolution"),
      g("si_12_5",  "[Both] SI onsite support active: response time SLA enforced"),
      g("si_12_6",  "[Internal] Instrumental software/imaging escalation path active and tested"),
      g("si_12_7",  "[Both] Spare parts inventory confirmed on-site or regionally by SI"),
      g("si_12_8",  "[Internal] If critical issues arise: remediation plan agreed; warranty window may be extended"),
      g("si_12_9",  "[Internal] Final payment milestone hold: last payment held until warranty window closes cleanly"),
      g("si_12_10", "[Internal] Legal review: confirm all contractual obligations met before closing deployment"),
    ], links: [], signatures: [] },
    { id: "si_ms_13", name: "13. Deployment Complete", description: "Formal closure, knowledge transfer, and ongoing ops.", color: "#059669", checklist: [
      g("si_13_1",  "[Internal] Warranty window closed with no outstanding critical issues"),
      g("si_13_2",  "[Internal] Final payment milestone released to SI"),
      g("si_13_3",  "[Both] Deployment formally accepted by all parties (Instrumental, SI, Customer, CM)"),
      g("si_13_4",  "[Internal] Deployment serial number and asset registered in deployment portal / webapp"),
      g("si_13_5",  "[Internal] Warranty start date, coverage scope, and SI SLA terms recorded in system of record"),
      g("si_13_6",  "[Internal] Approved drawing/spec revision logged in asset registry"),
      g("si_13_7",  "[Both] CM maintenance personnel trained on daily and preventative maintenance"),
      g("si_13_8",  "[Both] Troubleshooting guide provided to CM"),
      g("si_13_9",  "[Both] Escalation contacts documented: L1 CM POC > L2 SI POC > L3 Instrumental"),
      g("si_13_10", "[Internal] Quality data review cadence established (weekly/monthly)"),
      g("si_13_11", "[Internal] First article review completed; FPY, false alarm rate, process improvement metrics baselined"),
      g("si_13_12", "[Internal] Lessons learned documented; feedback incorporated into SIRD template"),
      g("si_13_13", "[Internal] SI scorecard updated: lead time, install quality, FAT first-pass rate, documentation quality"),
      g("si_13_14", "\"Instrumental Inside\" branding/sticker applied to deployed station (if applicable)"),
      g("si_13_15", "[Internal] Station hardening and source code protection verified post-deployment"),
    ], links: [], signatures: [
      { id: "si_sig_13_in",       role: "Instrumental", name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_13_si",       role: "SI",           name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_13_customer", role: "Customer",     name: "", email: "", signed: false, signedAt: null },
      { id: "si_sig_13_cm",       role: "CM",           name: "", email: "", signed: false, signedAt: null },
    ] },
  ],
};

function buildInstrumentalCategories(isSI) {
  const base = [
    { id: "inst_hw", name: "Hardware & MES Deployments", accessLevel: "open", items: [] },
    { id: "inst_specs", name: "Specifications & Integration Docs", accessLevel: "open", items: [] },
    { id: "inst_program", name: "Program Details & Timelines", accessLevel: "open", items: [], type: "program" },
    { id: "inst_training_docs", name: "Training Documentation", accessLevel: "open", items: [] },
  ];
  if (isSI) {
    base.push({ ...SI_CHECKLIST });
  } else {
    base.push({ ...INTERNAL_CHECKLIST });
    base.push({ ...EXTERNAL_CHECKLIST });
  }
  return base;
}

module.exports = { buildInstrumentalCategories, INTERNAL_CHECKLIST, EXTERNAL_CHECKLIST, SI_CHECKLIST };
